name: CI
on:
  - pull_request
  - push

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suite:
          - bundler
          - cargo
          - common
          - composer
          - dep
          - docker
          - elm
          - git_submodules
          - github_actions
          - go_modules
          - gradle
          - hex
          - maven
          - npm_and_yarn
          - nuget
          - omnibus
          - python
          - terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Pull Docker base image & warm Docker cache
        run: |
          docker pull "dependabot/dependabot-core:latest"
      - name: Set up Docker Buildx
        uses: satackey/action-docker-layer-caching@v0.0.4
      - name: Build dependabot-core image
        run: |
          docker build \
            -t "dependabot/dependabot-core:latest" \
            .
      - name: Build dependabot-core-ci image
        run: |
          rm .dockerignore
          docker build \
            -t "dependabot/dependabot-core-ci:${{ github.sha }}" \
            -f Dockerfile.ci \
            --cache-from "dependabot/dependabot-core:latest" \
            .
      - name: Run ${{ matrix.suite }} rspec specs
        run: |
          docker run --rm dependabot/dependabot-core-ci:${{ github.sha }} bash -c "cd /home/dependabot/dependabot-core/${{ matrix.suite }} && bundle exec rspec spec"
      - name: Run ${{ matrix.suite }} rubocop linting
        run: |
          docker run --rm dependabot/dependabot-core-ci:${{ github.sha }} bash -c "cd /home/dependabot/dependabot-core/${{ matrix.suite }} && bundle exec rubocop . -c ../.rubocop.yml"
      - name: Run javascript tests
        if: ${{ matrix.suite == "npm_and_yarn" }}
        run: |
          docker run --rm dependabot/dependabot-core-ci:${{ github.sha }} bash -c "cd /opt/npm_and_yarn && yarn lint"
          docker run --rm dependabot/dependabot-core-ci:${{ github.sha }} bash -c "cd /opt/npm_and_yarn && yarn test"
